global_frame: camera_odom_frame
rolling_window: true
track_unknown_space: true

inflation:
    inflation_radius: .1

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
