footprint: [[-0.5, -0.55], [-0.5, 0.55], [1.1, 0.55], [1.1, -0.55]]
robot_base_frame: base_link
resolution: 0.05
obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

static_wall:
    map_topic: /map_boundary
    subscribe_to_updates: false

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /os1_cloud_node/scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.7
    cost_scaling_factor: 3.0
    
