global_frame: map
update_frequency: 2
publish_frequency: 2
static_map: true
rolling_window: false
track_unknown_space: true

footprint_padding: 0.05

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}
