global_frame: os1_sensor
update_frequency: 8
publish_frequency: 8
rolling_window: true


plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
