global_frame: os1_sensor
rolling_window: true

inflation:
    inflation_radius: .5

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
