footprint: [[-0.5, -0.4], [-0.5, 0.4], [1.1, 0.45], [0.7, -0.6]]
footprint_padding: 0.01
robot_base_frame: base_link
resolution: 0.05
obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

static_wall:
    map_topic: /map_boundary
    subscribe_to_updates: false

obstacles_laser:
    observation_sources: laser fake_laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /os1_cloud_node/scan, inf_is_valid: true}
    fake_laser: {data_type: LaserScan, clearing: false, marking: true, topic: /os1_cloud_node/scan2, inf_is_valid: true}

inflation:
    inflation_radius: 0.6
    cost_scaling_factor: .01
    
