footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.1

robot_base_frame: base_link
update_frequency: 4
publish_frequency: 3
transform_tolerance: 1

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

static_wall:
    map_topic: /map_boundary
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /os1_cloud_node/scan, inf_is_valid: true}


